version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Monpasswordbiennetcommecamaislol
