version: '3'
services:
  postgres:
      image: postgres:latest
      container_name: postgres_container
      environment:
        POSTGRES_PASSWORD: oeoeoe
        POSTGRES_USER: streaming
        POSTGRES_DB: streaming
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
  app:
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Monpasswordbiennetcommecamaislol
